!=======================================================================
! Generated by  : PSCAD v4.2.1
!
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : Main
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE DSDyn()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------

      REAL    EMTDC_XINT    ! 'Integrator /w Interpolation'
!     SUBR    EMTDC_X2COMP  ! 'Comparator with Interpolation'
      REAL    LIMIT         ! Hard Limiter
      REAL    LDLGPOLE      ! Lead-Lag Function
!     SUBR    FILN15        ! Nth-order Butterworth/Chebyshev Filter
!     SUBR    EMTDC_XTTRANS  ! 'Timed Transition'
!     SUBR    3PHVSRC       ! 3-Phase Source model

!---------------------------------------
! Variable Declarations
!---------------------------------------


! Subroutine Parameters

! Electrical Node Indexes
      INTEGER NT_7, NT_9

! Control Signals
      INTEGER g4, g2, g6, IT_1, IT_2, IT_3
      REAL    RT_1, RT_2, RT_3, RT_4, RT_5, RT_6
      REAL    RT_7, RT_8, RT_9, RT_10, RT_11
      REAL    RT_12, RT_13, RT_14, RT_15, RT_16
      REAL    RT_17, RT_18, RT_19, RT_20, RT_21
      REAL    RT_22, RT_23, RT_24, RT_25, RT_26
      REAL    RT_27, RT_28, RT_29, RT_30, Eqctr
      REAL    RT_31, RT_32, g_boost, RT_33, RT_34
      REAL    RT_35, RT_36, RT_37, RT_38, RT_39
      REAL    RT_40, RT_41, RT_42, RT_43, RT_44
      REAL    RT_45, M_boost, g1, g3, g5, Theta1
      REAL    f, Va, Vb, Vc, Vab, Vbc, Vca, Ia
      REAL    Ib, Ic, Vtr, Edctr, Vq, Vd, Valpha
      REAL    Vbeta, Ectr_alpha, Ectr_beta, Theta
      REAL    Iq, Id, Ibeta, Ialpha, Vdlimit
      REAL    Iqerf, Vdcc, Vdccn, Iderf, Van, Vbn
      REAL    Vcn, Pout, Vbcn, Vcan, Vabn, Ian
      REAL    Ibn, Qout, Icn, scal, Ectr_c
      REAL    Ectr_b, Ectr_a, Ectr_apu, Ectr_bpu
      REAL    Ectr_cpu, RT_46, RT_47, RT_48
      REAL    RT_49, RT_50, RT_51, RT_52, RT_53
      REAL    RT_54, RT_55, RT_56, RT_57, RT_58
      REAL    RT_59, RT_60, RT_61, RT_62, RT_63
      REAL    RT_64, RT_65, RT_66, RT_67, RT_68
      REAL    RT_69, RT_70, RT_71, RT_72, RT_73
      REAL    RT_74, RT_75, RT_76, RT_77, RT_78
      REAL    RT_79, RT_80, RT_81, RT_82, RT_83
      REAL    RT_84, RT_85, RT_86, RT_87, RT_88
      REAL    RT_89, RT_90, RT_91, RT_92, RT_93
      REAL    RT_94, RT_95, RT_96, RT_97, RT_98
      REAL    RT_99, RT_100, RT_101, RT_102
      REAL    RT_103, RT_104, Vpv

! Internal Variables
      REAL    RVD2_1(2), RVD2_2(2), C_INST, C_MAG
      REAL    E_MAG, F_RAD, R_PH

! Indexing variables
      INTEGER ISTOI, ISTOF, IT_0                  ! Storage Indexes
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr


!---------------------------------------
! Record local indexes
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage
      NTXFR = NTXFR + 1
      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF

! Record Offset and Increment Storage Counters
      ISTOI     = NSTOI
      NSTOI     = NSTOI + 6
      ISTOF     = NSTOF
      NSTOF     = NSTOF + 158
      IPGB      = NPGB
      NPGB      = NPGB + 32
      INODE     = NNODE + 2
      NNODE     = NNODE + 18

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO 100  IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
  100 CONTINUE

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 33

!---------------------------------------
! Transfers from storage arrays
!---------------------------------------

      RT_1     = STOF(ISTOF + 1)
      RT_2     = STOF(ISTOF + 2)
      RT_3     = STOF(ISTOF + 3)
      RT_4     = STOF(ISTOF + 4)
      RT_5     = STOF(ISTOF + 5)
      RT_6     = STOF(ISTOF + 6)
      RT_7     = STOF(ISTOF + 7)
      RT_8     = STOF(ISTOF + 8)
      RT_9     = STOF(ISTOF + 9)
      RT_10    = STOF(ISTOF + 10)
      RT_11    = STOF(ISTOF + 11)
      RT_12    = STOF(ISTOF + 12)
      RT_13    = STOF(ISTOF + 13)
      RT_14    = STOF(ISTOF + 14)
      RT_15    = STOF(ISTOF + 15)
      RT_16    = STOF(ISTOF + 16)
      RT_17    = STOF(ISTOF + 17)
      RT_18    = STOF(ISTOF + 18)
      RT_19    = STOF(ISTOF + 19)
      RT_20    = STOF(ISTOF + 20)
      RT_21    = STOF(ISTOF + 21)
      RT_22    = STOF(ISTOF + 22)
      RT_23    = STOF(ISTOF + 23)
      RT_24    = STOF(ISTOF + 24)
      RT_25    = STOF(ISTOF + 25)
      RT_26    = STOF(ISTOF + 26)
      RT_27    = STOF(ISTOF + 27)
      RT_28    = STOF(ISTOF + 28)
      RT_29    = STOF(ISTOF + 29)
      RT_30    = STOF(ISTOF + 30)
      Eqctr    = STOF(ISTOF + 31)
      RT_31    = STOF(ISTOF + 32)
      RT_32    = STOF(ISTOF + 33)
      g_boost  = STOF(ISTOF + 34)
      RT_33    = STOF(ISTOF + 35)
      RT_34    = STOF(ISTOF + 36)
      RT_35    = STOF(ISTOF + 37)
      RT_36    = STOF(ISTOF + 38)
      RT_37    = STOF(ISTOF + 39)
      RT_38    = STOF(ISTOF + 40)
      RT_39    = STOF(ISTOF + 41)
      RT_40    = STOF(ISTOF + 42)
      RT_41    = STOF(ISTOF + 43)
      RT_42    = STOF(ISTOF + 44)
      RT_43    = STOF(ISTOF + 45)
      RT_44    = STOF(ISTOF + 46)
      RT_45    = STOF(ISTOF + 47)
      M_boost  = STOF(ISTOF + 48)
      g4       = STOI(ISTOI + 1)
      g1       = STOF(ISTOF + 49)
      g3       = STOF(ISTOF + 50)
      g5       = STOF(ISTOF + 51)
      g2       = STOI(ISTOI + 2)
      g6       = STOI(ISTOI + 3)
      Theta1   = STOF(ISTOF + 52)
      f        = STOF(ISTOF + 53)
      Va       = STOF(ISTOF + 54)
      Vb       = STOF(ISTOF + 55)
      Vc       = STOF(ISTOF + 56)
      Vab      = STOF(ISTOF + 57)
      Vbc      = STOF(ISTOF + 58)
      Vca      = STOF(ISTOF + 59)
      Ia       = STOF(ISTOF + 60)
      Ib       = STOF(ISTOF + 61)
      Ic       = STOF(ISTOF + 62)
      Vtr      = STOF(ISTOF + 63)
      Edctr    = STOF(ISTOF + 64)
      Vq       = STOF(ISTOF + 65)
      Vd       = STOF(ISTOF + 66)
      Valpha   = STOF(ISTOF + 67)
      Vbeta    = STOF(ISTOF + 68)
      Ectr_alpha = STOF(ISTOF + 69)
      Ectr_beta = STOF(ISTOF + 70)
      Theta    = STOF(ISTOF + 71)
      Iq       = STOF(ISTOF + 72)
      Id       = STOF(ISTOF + 73)
      Ibeta    = STOF(ISTOF + 74)
      Ialpha   = STOF(ISTOF + 75)
      Vdlimit  = STOF(ISTOF + 76)
      Iqerf    = STOF(ISTOF + 77)
      Vdcc     = STOF(ISTOF + 78)
      Vdccn    = STOF(ISTOF + 79)
      Iderf    = STOF(ISTOF + 80)
      Van      = STOF(ISTOF + 81)
      Vbn      = STOF(ISTOF + 82)
      Vcn      = STOF(ISTOF + 83)
      Pout     = STOF(ISTOF + 84)
      Vbcn     = STOF(ISTOF + 85)
      Vcan     = STOF(ISTOF + 86)
      Vabn     = STOF(ISTOF + 87)
      Ian      = STOF(ISTOF + 88)
      Ibn      = STOF(ISTOF + 89)
      Qout     = STOF(ISTOF + 90)
      Icn      = STOF(ISTOF + 91)
      scal     = STOF(ISTOF + 92)
      Ectr_c   = STOF(ISTOF + 93)
      Ectr_b   = STOF(ISTOF + 94)
      Ectr_a   = STOF(ISTOF + 95)
      Ectr_apu = STOF(ISTOF + 96)
      Ectr_bpu = STOF(ISTOF + 97)
      Ectr_cpu = STOF(ISTOF + 98)
      RT_46    = STOF(ISTOF + 99)
      RT_47    = STOF(ISTOF + 100)
      RT_48    = STOF(ISTOF + 101)
      IT_1     = STOI(ISTOI + 4)
      IT_2     = STOI(ISTOI + 5)
      IT_3     = STOI(ISTOI + 6)
      RT_49    = STOF(ISTOF + 102)
      RT_50    = STOF(ISTOF + 103)
      RT_51    = STOF(ISTOF + 104)
      RT_52    = STOF(ISTOF + 105)
      RT_53    = STOF(ISTOF + 106)
      RT_54    = STOF(ISTOF + 107)
      RT_55    = STOF(ISTOF + 108)
      RT_56    = STOF(ISTOF + 109)
      RT_57    = STOF(ISTOF + 110)
      RT_58    = STOF(ISTOF + 111)
      RT_59    = STOF(ISTOF + 112)
      RT_60    = STOF(ISTOF + 113)
      RT_61    = STOF(ISTOF + 114)
      RT_62    = STOF(ISTOF + 115)
      RT_63    = STOF(ISTOF + 116)
      RT_64    = STOF(ISTOF + 117)
      RT_65    = STOF(ISTOF + 118)
      RT_66    = STOF(ISTOF + 119)
      RT_67    = STOF(ISTOF + 120)
      RT_68    = STOF(ISTOF + 121)
      RT_69    = STOF(ISTOF + 122)
      RT_70    = STOF(ISTOF + 123)
      RT_71    = STOF(ISTOF + 124)
      RT_72    = STOF(ISTOF + 125)
      RT_73    = STOF(ISTOF + 126)
      RT_74    = STOF(ISTOF + 127)
      RT_75    = STOF(ISTOF + 128)
      RT_76    = STOF(ISTOF + 129)
      RT_77    = STOF(ISTOF + 130)
      RT_78    = STOF(ISTOF + 131)
      RT_79    = STOF(ISTOF + 132)
      RT_80    = STOF(ISTOF + 133)
      RT_81    = STOF(ISTOF + 134)
      RT_82    = STOF(ISTOF + 135)
      RT_83    = STOF(ISTOF + 136)
      RT_84    = STOF(ISTOF + 137)
      RT_85    = STOF(ISTOF + 138)
      RT_86    = STOF(ISTOF + 139)
      RT_87    = STOF(ISTOF + 140)
      RT_88    = STOF(ISTOF + 141)
      RT_89    = STOF(ISTOF + 142)
      RT_90    = STOF(ISTOF + 143)
      RT_91    = STOF(ISTOF + 144)
      RT_92    = STOF(ISTOF + 145)
      RT_93    = STOF(ISTOF + 146)
      RT_94    = STOF(ISTOF + 147)
      RT_95    = STOF(ISTOF + 148)
      RT_96    = STOF(ISTOF + 149)
      RT_97    = STOF(ISTOF + 150)
      RT_98    = STOF(ISTOF + 151)
      RT_99    = STOF(ISTOF + 152)
      RT_100   = STOF(ISTOF + 153)
      RT_101   = STOF(ISTOF + 154)
      RT_102   = STOF(ISTOF + 155)
      RT_103   = STOF(ISTOF + 156)
      RT_104   = STOF(ISTOF + 157)
      Vpv      = STOF(ISTOF + 158)

!---------------------------------------
! Transfer from Imports
!---------------------------------------


!---------------------------------------
! Electrical Node Lookup
!---------------------------------------

      NT_7  = NODE(INODE + 7)
      NT_9  = NODE(INODE + 9)

!---------------------------------------
! Read Model data (if any)
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Main.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF

!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 140:[const] Real Constant 
      RT_77 = 0.5

! 190:[const] Real Constant 
      RT_78 = 0.866

! 200:[const] Real Constant 
      RT_81 = 1.0

! 220:[const] Real Constant 
      RT_45 = 408.0

! 250:[const] Real Constant 
      RT_79 = 0.5

! 270:[const] Real Constant 
      RT_82 = 0.0

! 280:[const] Real Constant 
      RT_104 = 1.0

! 300:[div] Divider 
!
      IF (ABS(RT_45) .LT. 1.0E-10) THEN
         IF (RT_45 .LT. 0.0)  THEN
            scal = -1.0E10 * RT_104
         ELSE
            scal =  1.0E10 * RT_104
         ENDIF
      ELSE
         scal = RT_104 / RT_45
      ENDIF
!

! 320:[const] Real Constant 
      RT_51 = 100.0

! 330:[emtconst] Commonly Used Constants (pi...) 
      RT_59 = TWO_3RD

! 340:[const] Real Constant 
      RT_80 = 0.866

! 350:[const] Real Constant 
      RT_50 = 50.0

! 360:[mult] Multiplier 
!
      RT_49 = RT_50 * RT_51
!

! 370:[sig_gen] Variable Frequency Sawtooth Generator 
!  SIGNAL GENERATOR
      IF ( TIMEZERO ) THEN
         STOR(NEXC+2) = 1
         Vtr = ((1.0)+(-1.0))*0.5
      ELSE
         Vtr=STOR(NEXC+1)+STOR(NEXC+2)*4.0*RT_49*DELT
         IF (Vtr.GT.(1.0)) THEN
            Vtr=2*(1.0)-Vtr
            STOR(NEXC+2)=-1
         ENDIF
         IF (Vtr.LT.(-1.0)) THEN
            Vtr=2.0*(-1.0)-Vtr
            STOR(NEXC+2)=1
         ENDIF
      ENDIF
      STOR(NEXC+1)=Vtr
      NEXC=NEXC+2
!

! 380:[pgb] Output Channel '<Untitled>'

      PGB(IPGB+7) = Vtr

! 390:[emtconst] Commonly Used Constants (pi...) 
      RT_57 = TWO_PI

! 400:[emtconst] Commonly Used Constants (pi...) 
      RT_54 = TWO_PI

! 410:[emtconst] Commonly Used Constants (pi...) 
      RT_60 = ONE_3RD

! 440:[const] Real Constant 
      RT_55 = 50.0

! 450:[const] Real Constant 
      RT_52 = 0.0

! 460:[emtconst] Commonly Used Constants (pi...) 
      RT_61 = ONE_3RD

! 470:[emtconst] Commonly Used Constants (pi...) 
      RT_92 = TWO_3RD

! 480:[const] Real Constant 
      RT_89 = 0.0

! 490:[mult] Multiplier 
!
      RT_26 = RT_92 * Ian
!

! 500:[mult] Multiplier 
!
      RT_23 = RT_89 * Ian
!

! 510:[const] Real Constant 
      RT_62 = 0.0

! 520:[emtconst] Commonly Used Constants (pi...) 
      RT_93 = ONE_3RD

! 530:[emtconst] Commonly Used Constants (pi...) 
      RT_90 = SQRT_1BY3

! 540:[mult] Multiplier 
!
      RT_27 = RT_93 * Ibn
!

! 550:[mult] Multiplier 
!
      RT_24 = RT_90 * Ibn
!

! 560:[emtconst] Commonly Used Constants (pi...) 
      RT_63 = SQRT_1BY3

! 570:[emtconst] Commonly Used Constants (pi...) 
      RT_94 = ONE_3RD

! 580:[mult] Multiplier 
!
      RT_28 = RT_94 * Icn
!

! 590:[emtconst] Commonly Used Constants (pi...) 
      RT_91 = SQRT_1BY3

! 600:[mult] Multiplier 
!
      RT_25 = RT_91 * Icn
!

! 610:[emtconst] Commonly Used Constants (pi...) 
      RT_64 = SQRT_1BY3

! 620:[const] Real Constant 
      M_boost = 0.25

! 630:[const] Real Constant 
      RT_98 = 5000.0

! 650:[sig_gen] Variable Frequency Sawtooth Generator 
!  SIGNAL GENERATOR
      IF ( TIMEZERO ) THEN
         STOR(NEXC+2) = 1
         RT_32 = ((1.0)+(0.0))*0.5
      ELSE
         RT_32=STOR(NEXC+1)+STOR(NEXC+2)*2.0*RT_98*DELT
         IF (RT_32.GT.(1.0)) THEN
            RT_32=2*(1.0)-RT_32
            STOR(NEXC+2)=-1
         ENDIF
         IF (RT_32.LT.(0.0)) THEN
            RT_32=2.0*(0.0)-RT_32
            STOR(NEXC+2)=1
         ENDIF
      ENDIF
      STOR(NEXC+1)=RT_32
      NEXC=NEXC+2
!

! 670:[const] Real Constant 
      RT_100 = 0.0

! 690:[const] Real Constant 
      RT_101 = 816.0

! 700:[sumjct] Summing/Differencing Junctions 
      RT_34 = - RT_101 + Vdccn
!

! 710:[gain] Gain Block 
!  Gain
      RT_35 = 0.09 * RT_34
!

! 720:[integral] Interpolated Integrator 
      RVD2_1(1) = RT_35
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
!
      RT_36 = EMTDC_XINT(0, 0, 0, 0.0, 1.0, 0.0,-1000.0, 1000.0,RVD2_2,R&
     &VD2_1)

! 730:[emtconst] Commonly Used Constants (pi...) 
      RT_33 = TWO_3RD

! 740:[emtconst] Commonly Used Constants (pi...) 
      RT_103 = SQRT_1BY3

! 750:[gain] Gain Block 
!  Gain
      RT_44 = -1.0 * RT_103
!

! 760:[gain] Gain Block 
!  Gain
      RT_37 = 0.6 * RT_34
!

! 800:[mult] Multiplier 
!
      RT_3 = RT_59 * Van
!

! 810:[mult] Multiplier 
!
      RT_20 = RT_54 * RT_55
!

! 820:[mult] Multiplier 
!
      RT_4 = RT_60 * Vbn
!

! 830:[mult] Multiplier 
!
      RT_5 = RT_61 * Vcn
!

! 840:[sumjct] Summing/Differencing Junctions 
      Ialpha = + RT_26 - RT_27 - RT_28
!

! 850:[sumjct] Summing/Differencing Junctions 
      Ibeta = + RT_23 + RT_24 - RT_25
!

! 860:[mult] Multiplier 
!
      RT_6 = RT_62 * Van
!

! 870:[mult] Multiplier 
!
      RT_7 = RT_63 * Vbn
!

! 880:[mult] Multiplier 
!
      RT_8 = RT_64 * Vcn
!

! 900:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,M_boost,RT_32,1.0,0.0,0.0,RVD2_1)
      g_boost = RVD2_1(1)

! 930:[sumjct] Summing/Differencing Junctions 
      Iderf = + RT_36 + RT_37
!

! 940:[sumjct] Summing/Differencing Junctions 
      Valpha = + RT_3 - RT_4 - RT_5
!

! 950:[sumjct] Summing/Differencing Junctions 
      Vbeta = + RT_6 + RT_7 - RT_8
!

! 960:[trig] Trigonometric Functions 
!  Trig-Func
      RT_71 = SIN(Theta)
!

! 970:[mult] Multiplier 
!
      RT_72 = RT_71 * Valpha
!

! 980:[sumjct] Summing/Differencing Junctions 
      RT_19 = + RT_53 + RT_20
!

! 990:[integral] Interpolated Integrator 
      RVD2_1(1) = RT_19
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
!
      Theta = EMTDC_XINT(0, 0, 0, 0.0, 1.0, 0.0,-100000000.0, 100000000.&
     &0,RVD2_2,RVD2_1)

! 1000:[trig] Trigonometric Functions 
!  Trig-Func
      RT_73 = COS(Theta)
!

! 1010:[mult] Multiplier 
!
      RT_11 = RT_73 * Vbeta
!

! 1020:[sumjct] Summing/Differencing Junctions 
      Vq = - RT_72 + RT_11
!

! 1030:[sumjct] Summing/Differencing Junctions 
      RT_1 = + Vq - RT_52
!

! 1040:[gain] Gain Block 
!  Gain
      RT_47 = 1269.4 * RT_1
!

! 1050:[integral] Interpolated Integrator 
      RVD2_1(1) = RT_47
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
!
      RT_48 = EMTDC_XINT(0, 0, 0, 0.0, 1.0, 0.0,-100000000.0, 100000000.&
     &0,RVD2_2,RVD2_1)

! 1060:[gain] Gain Block 
!  Gain
      RT_2 = 2.856 * RT_1
!

! 1070:[sumjct] Summing/Differencing Junctions 
      RT_53 = + RT_48 + RT_2
!

! 1080:[trig] Trigonometric Functions 
!  Trig-Func
      RT_74 = COS(Theta)
!

! 1090:[trig] Trigonometric Functions 
!  Trig-Func
      RT_76 = SIN(Theta)
!

! 1100:[mult] Multiplier 
!
      RT_75 = RT_74 * Valpha
!

! 1110:[trig] Trigonometric Functions 
!  Trig-Func
      RT_86 = SIN(Theta)
!

! 1120:[mult] Multiplier 
!
      RT_12 = RT_76 * Vbeta
!

! 1130:[sumjct] Summing/Differencing Junctions 
      Vd = + RT_75 + RT_12
!

! 1140:[trig] Trigonometric Functions 
!  Trig-Func
      RT_88 = COS(Theta)
!

! 1150:[mult] Multiplier 
!
      RT_87 = RT_86 * Ialpha
!

! 1160:[trig] Trigonometric Functions 
!  Trig-Func
      RT_83 = COS(Theta)
!

! 1170:[hardlimit] Hard Limiter 
!  Hard_Limit
      Vdlimit = LIMIT(-400.0, 400.0, Vd)
!

! 1180:[div] Divider 
!
      IF (ABS(Vdlimit) .LT. 1.0E-10) THEN
         IF (Vdlimit .LT. 0.0)  THEN
            RT_99 = -1.0E10 * RT_100
         ELSE
            RT_99 =  1.0E10 * RT_100
         ENDIF
      ELSE
         RT_99 = RT_100 / Vdlimit
      ENDIF
!

! 1190:[mult] Multiplier 
!
      RT_22 = RT_88 * Ibeta
!

! 1200:[trig] Trigonometric Functions 
!  Trig-Func
      RT_85 = SIN(Theta)
!

! 1210:[sumjct] Summing/Differencing Junctions 
      Iq = - RT_87 + RT_22
!

! 1220:[mult] Multiplier 
!
      RT_84 = RT_83 * Ialpha
!

! 1230:[mult] Multiplier 
!
      Iqerf = RT_99 * RT_33
!

! 1240:[mult] Multiplier 
!
      RT_21 = RT_85 * Ibeta
!

! 1250:[sumjct] Summing/Differencing Junctions 
      RT_31 = + Iqerf - Iq
!

! 1260:[gain] Gain Block 
!  Gain
      RT_96 = 177.19 * RT_31
!

! 1270:[sumjct] Summing/Differencing Junctions 
      Id = + RT_84 + RT_21
!

! 1280:[sumjct] Summing/Differencing Junctions 
      RT_46 = + Iderf - Id
!

! 1290:[integral] Interpolated Integrator 
      RVD2_1(1) = RT_96
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
!
      RT_97 = EMTDC_XINT(0, 0, 0, 0.0, 1.0, 0.0,-500.0, 500.0,RVD2_2,RVD&
     &2_1)

! 1300:[gain] Gain Block 
!  Gain
      RT_58 = 64.57 * RT_46
!

! 1310:[leadlag] Lead-Lag 
!  Lead_Lag
      RT_30 = LDLGPOLE(0,1,0,0.0002376,1.7058e-005,1.0,RT_97,0.0,-10.0,1&
     &0.0)

! 1320:[integral] Interpolated Integrator 
      RVD2_1(1) = RT_58
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
!
      RT_95 = EMTDC_XINT(0, 0, 0, 0.0, 1.0, 0.0,-500.0, 500.0,RVD2_2,RVD&
     &2_1)

! 1330:[trig] Trigonometric Functions 
!  Trig-Func
      RT_68 = SIN(Theta)
!

! 1340:[hardlimit] Hard Limiter 
!  Hard_Limit
      Eqctr = LIMIT(-400.0, 400.0, RT_30)
!

! 1350:[leadlag] Lead-Lag 
!  Lead_Lag
      RT_29 = LDLGPOLE(0,1,0,0.0004835,8.382e-006,1.0,RT_95,0.0,-10.0,10&
     &.0)

! 1360:[trig] Trigonometric Functions 
!  Trig-Func
      RT_70 = COS(Theta)
!

! 1370:[trig] Trigonometric Functions 
!  Trig-Func
      RT_65 = SIN(Theta)
!

! 1380:[mult] Multiplier 
!
      RT_69 = RT_68 * Eqctr
!

! 1390:[hardlimit] Hard Limiter 
!  Hard_Limit
      Edctr = LIMIT(-400.0, 400.0, RT_29)
!

! 1400:[trig] Trigonometric Functions 
!  Trig-Func
      RT_67 = COS(Theta)
!

! 1410:[mult] Multiplier 
!
      RT_10 = RT_70 * Edctr
!

! 1420:[mult] Multiplier 
!
      RT_66 = RT_65 * Edctr
!

! 1430:[sumjct] Summing/Differencing Junctions 
      Ectr_alpha = - RT_69 + RT_10
!

! 1440:[mult] Multiplier 
!
      RT_15 = RT_79 * Ectr_alpha
!

! 1450:[mult] Multiplier 
!
      RT_13 = RT_77 * Ectr_alpha
!

! 1460:[mult] Multiplier 
!
      RT_9 = RT_67 * Eqctr
!

! 1470:[sumjct] Summing/Differencing Junctions 
      Ectr_beta = + RT_66 + RT_9
!

! 1480:[mult] Multiplier 
!
      RT_16 = RT_80 * Ectr_beta
!

! 1490:[sumjct] Summing/Differencing Junctions 
      Ectr_c = - RT_15 - RT_16
!

! 1500:[mult] Multiplier 
!
      RT_17 = RT_81 * Ectr_alpha
!

! 1510:[mult] Multiplier 
!
      RT_14 = RT_78 * Ectr_beta
!

! 1520:[sumjct] Summing/Differencing Junctions 
      Ectr_b = - RT_13 + RT_14
!

! 1530:[trans_filt] Nth Order Butterworth/Chebyshev Filter 
!
!  BUTTERWORTH FILTER
!
      CALL FILN15(2,60.0,0.0, 0.0 ,1,1,0,RT_19,RT_56)
!

! 1540:[mult] Multiplier 
!
      Ectr_cpu = scal * Ectr_c
!

! 1550:[mult] Multiplier 
!
      RT_18 = RT_82 * Ectr_beta
!

! 1560:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,Ectr_cpu,Vtr,1.0,0.0,0.0,RVD2_1)
      g5 = RVD2_1(1)

! 1570:[mult] Multiplier 
!
      Ectr_bpu = scal * Ectr_b
!

! 1580:[sumjct] Summing/Differencing Junctions 
      Ectr_a = + RT_17 + RT_18
!

! 1590:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,Ectr_bpu,Vtr,1.0,0.0,0.0,RVD2_1)
      g3 = RVD2_1(1)

! 1600:[mult] Multiplier 
!
      Ectr_apu = scal * Ectr_a
!

! 1610:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,Ectr_apu,Vtr,1.0,0.0,0.0,RVD2_1)
      g1 = RVD2_1(1)

! 1620:[div] Divider 
!
      IF (ABS(RT_57) .LT. 1.0E-10) THEN
         IF (RT_57 .LT. 0.0)  THEN
            f = -1.0E10 * RT_56
         ELSE
            f =  1.0E10 * RT_56
         ENDIF
      ELSE
         f = RT_56 / RT_57
      ENDIF
!

! 1630:[inv] Interpolated Logic Inverter 
      IF (NINT(g5) .NE. 0) THEN
         IT_3 = 0
      ELSE
         IT_3 = 1
      ENDIF

! 1640:[inv] Interpolated Logic Inverter 
      IF (NINT(g3) .NE. 0) THEN
         IT_2 = 0
      ELSE
         IT_2 = 1
      ENDIF

! 1650:[inv] Interpolated Logic Inverter 
      IF (NINT(g1) .NE. 0) THEN
         IT_1 = 0
      ELSE
         IT_1 = 1
      ENDIF

! 1660:[pgb] Output Channel 'Idref'

      PGB(IPGB+9) = Iderf

! 1670:[pgb] Output Channel 'Iqref'

      PGB(IPGB+10) = Iqerf

! 1690:[mult] Multiplier 
!
      Qout = RT_102 * RT_44
!

! 1710:[pgb] Output Channel 'G_boost '

      PGB(IPGB+11) = g_boost

! 1720:[pgb] Output Channel 'Valpha'

      PGB(IPGB+12) = Ectr_beta

! 1730:[pgb] Output Channel 'Valpha'

      PGB(IPGB+13) = Ectr_alpha

! 1740:[pgb] Output Channel 'Vd'

      PGB(IPGB+14) = Vd

! 1750:[pgb] Output Channel 'Vq'

      PGB(IPGB+15) = Vq

! 1760:[pgb] Output Channel 'Eqctr'

      PGB(IPGB+16) = Eqctr

! 1770:[pgb] Output Channel 'Iq'

      PGB(IPGB+17) = Iq

! 1780:[pgb] Output Channel 'Id'

      PGB(IPGB+18) = Id

! 1790:[pgb] Output Channel 'Vq'

      PGB(IPGB+19) = Vdlimit

! 1800:[pgb] Output Channel 'Edcr'

      PGB(IPGB+20) = Edctr

! 1810:[pgb] Output Channel 'Vbeta '

      PGB(IPGB+21) = Vbeta

! 1820:[integral] Interpolated Integrator 
      RVD2_1(1) = RT_53
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
!
      Theta1 = EMTDC_XINT(0, 0, 0, 0.0, 0.001, 0.0,-100000000.0, 1000000&
     &00.0,RVD2_2,RVD2_1)

! 1830:[pgb] Output Channel '<Untitled>'

      PGB(IPGB+22) = Theta

! 1840:[pgb] Output Channel 'Frequancy'

      PGB(IPGB+23) = f

! 1860:[pgb] Output Channel 'Qout'

      PGB(IPGB+25) = Qout

! 1870:[pgb] Output Channel 'Valpha '

      PGB(IPGB+26) = Valpha

! 1880:[pgb] Output Channel 'Ectrc'

      PGB(IPGB+27) = Ectr_c

! 1890:[bin_delay] Timed ON/OFF Logic Transition 
!
      RVD2_1(1) = IT_3
      RVD2_1(2) = 0.0
!
      CALL EMTDC_XTTRANS(0,5.0e-006,0.0,RVD2_1,RVD2_2)
!
      g2 = RVD2_2(1)

! 1900:[pgb] Output Channel 'Ectra'

      PGB(IPGB+28) = Ectr_a

! 1910:[bin_delay] Timed ON/OFF Logic Transition 
!
      RVD2_1(1) = IT_2
      RVD2_1(2) = 0.0
!
      CALL EMTDC_XTTRANS(0,5.0e-006,0.0,RVD2_1,RVD2_2)
!
      g6 = RVD2_2(1)

! 1920:[pgb] Output Channel 'Ectrb'

      PGB(IPGB+29) = Ectr_b

! 1930:[bin_delay] Timed ON/OFF Logic Transition 
!
      RVD2_1(1) = IT_1
      RVD2_1(2) = 0.0
!
      CALL EMTDC_XTTRANS(0,5.0e-006,0.0,RVD2_1,RVD2_2)
!
      g4 = RVD2_2(1)

! 1940:[peswitch] Power electronic switch 
! EMTDC_PESWITCH Power Electronic Switch Model: IGBT
      CALL EMTDC_PESWITCH2(SS(1),  (IBRCH(1)+11), 0.01, 1000000.0, g4, 0&
     &.0, 3, 0, 100000.0, 100000.0, 0.0, 0.0)

! 1960:[peswitch] Power electronic switch 
! EMTDC_PESWITCH Power Electronic Switch Model: IGBT
      CALL EMTDC_PESWITCH2(SS(1),  (IBRCH(1)+7), 0.01, 1000000.0, g6, 0.&
     &0, 3, 0, 100000.0, 100000.0, 0.0, 0.0)

! 1970:[peswitch] Power electronic switch 
! EMTDC_PESWITCH Power Electronic Switch Model: IGBT
      CALL EMTDC_PESWITCH2(SS(1),  (IBRCH(1)+3), 0.01, 1000000.0, g2, 0.&
     &0, 3, 0, 100000.0, 100000.0, 0.0, 0.0)

! 1990:[peswitch] Power electronic switch 
! EMTDC_PESWITCH Power Electronic Switch Model: IGBT
      CALL EMTDC_PESWITCH2(SS(1),  (IBRCH(1)+15), 0.01, 1000000.0, NINT(&
     &g_boost), 0.0, 3, 0, 100000.0, 100000.0, 0.0, 0.0)

! 2010:[peswitch] Power electronic switch 
! EMTDC_PESWITCH Power Electronic Switch Model: IGBT
      CALL EMTDC_PESWITCH2(SS(1),  (IBRCH(1)+9), 0.01, 1000000.0, NINT(g&
     &1), 0.0, 3, 0, 100000.0, 100000.0, 0.0, 0.0)

! 2020:[peswitch] Power electronic switch 
! EMTDC_PESWITCH Power Electronic Switch Model: IGBT
      CALL EMTDC_PESWITCH2(SS(1),  (IBRCH(1)+5), 0.01, 1000000.0, NINT(g&
     &3), 0.0, 3, 0, 100000.0, 100000.0, 0.0, 0.0)

! 2030:[peswitch] Power electronic switch 
! EMTDC_PESWITCH Power Electronic Switch Model: IGBT
      CALL EMTDC_PESWITCH2(SS(1),  (IBRCH(1)+1), 0.01, 1000000.0, NINT(g&
     &5), 0.0, 3, 0, 100000.0, 100000.0, 0.0, 0.0)

! -1:[peswitch] Power electronic switch 
! EMTDC_PESWITCH Power Electronic Switch Model: Diode
      CALL EMTDC_PESWITCH2(SS(1),  (IBRCH(1)+13), 0.01, 1000000.0, 1, 0.&
     &0, 0, 0, 100000.0, 100000.0, 0.0, 0.0)

! -1:[src_ccin_1] Current Source 'Source 1'
!  Single Phase Current Source.
      IF ( TIME .GT. 0.005 ) THEN
         C_MAG = 0.05
      ELSE
         C_MAG = 10.0*TIME
      ENDIF
      C_INST = C_MAG
      IF (NT_9 .NE. 0) CCIN(NT_9, SS(1)) = CCIN(NT_9, SS(1)) + C_INST
      IF (NT_7 .NE. 0) CCIN(NT_7, SS(1)) = CCIN(NT_7, SS(1)) - C_INST
!
      IF (TIMEZERO) THEN
         IF (NT_9 .NE. 0) ENABCCIN(NT_9,SS(1)) = .TRUE.
         IF (NT_7 .NE. 0) ENABCCIN(NT_7,SS(1)) = .TRUE.
      ENDIF
!

! -1:[peswitch] Power electronic switch 
! EMTDC_PESWITCH Power Electronic Switch Model: Diode
      CALL EMTDC_PESWITCH2(SS(1),  (IBRCH(1)+2), 0.01, 1000000.0, 1, 0.0&
     &, 0, 0, 100000.0, 100000.0, 0.0, 0.0)

! -1:[peswitch] Power electronic switch 
! EMTDC_PESWITCH Power Electronic Switch Model: Diode
      CALL EMTDC_PESWITCH2(SS(1),  (IBRCH(1)+6), 0.01, 1000000.0, 1, 0.0&
     &, 0, 0, 100000.0, 100000.0, 0.0, 0.0)

! -1:[peswitch] Power electronic switch 
! EMTDC_PESWITCH Power Electronic Switch Model: Diode
      CALL EMTDC_PESWITCH2(SS(1),  (IBRCH(1)+10), 0.01, 1000000.0, 1, 0.&
     &0, 0, 0, 100000.0, 100000.0, 0.0, 0.0)

! -1:[peswitch] Power electronic switch 
! EMTDC_PESWITCH Power Electronic Switch Model: Diode
      CALL EMTDC_PESWITCH2(SS(1),  (IBRCH(1)+14), 0.01, 1000000.0, 1, 0.&
     &0, 0, 0, 100000.0, 100000.0, 0.0, 0.0)

! -1:[source_3] Three Phase Voltage Source Model 2 'Source 1'
! Three Phase Source: Source 1  Type: L
!  Mag: 0.311085197333 kV, Freq: 50.0 Hz, Phase: 0.0 degs, StartUp: 0.05 sec
      E_MAG = 0.311085197333
      F_RAD = 314.159265359
      R_PH  = 0.0*PI_BY180
      CALL EMTDC_3PHVSRC(SS(1), (IBRCH(1)+21), (IBRCH(1)+20), (IBRCH(1)+&
     &19), 0.05, .TRUE., E_MAG , F_RAD, R_PH)
!

! -1:[peswitch] Power electronic switch 
! EMTDC_PESWITCH Power Electronic Switch Model: Diode
      CALL EMTDC_PESWITCH2(SS(1),  (IBRCH(1)+4), 0.01, 1000000.0, 1, 0.0&
     &, 0, 0, 100000.0, 100000.0, 0.0, 0.0)

! -1:[peswitch] Power electronic switch 
! EMTDC_PESWITCH Power Electronic Switch Model: Diode
      CALL EMTDC_PESWITCH2(SS(1),  (IBRCH(1)+8), 0.01, 1000000.0, 1, 0.0&
     &, 0, 0, 100000.0, 100000.0, 0.0, 0.0)

! -1:[peswitch] Power electronic switch 
! EMTDC_PESWITCH Power Electronic Switch Model: Diode
      CALL EMTDC_PESWITCH2(SS(1),  (IBRCH(1)+12), 0.01, 1000000.0, 1, 0.&
     &0, 0, 0, 100000.0, 100000.0, 0.0, 0.0)

!---------------------------------------
! Feedbacks and transfers to storage
!---------------------------------------

      STOF(ISTOF + 1) = RT_1
      STOF(ISTOF + 2) = RT_2
      STOF(ISTOF + 3) = RT_3
      STOF(ISTOF + 4) = RT_4
      STOF(ISTOF + 5) = RT_5
      STOF(ISTOF + 6) = RT_6
      STOF(ISTOF + 7) = RT_7
      STOF(ISTOF + 8) = RT_8
      STOF(ISTOF + 9) = RT_9
      STOF(ISTOF + 10) = RT_10
      STOF(ISTOF + 11) = RT_11
      STOF(ISTOF + 12) = RT_12
      STOF(ISTOF + 13) = RT_13
      STOF(ISTOF + 14) = RT_14
      STOF(ISTOF + 15) = RT_15
      STOF(ISTOF + 16) = RT_16
      STOF(ISTOF + 17) = RT_17
      STOF(ISTOF + 18) = RT_18
      STOF(ISTOF + 19) = RT_19
      STOF(ISTOF + 20) = RT_20
      STOF(ISTOF + 21) = RT_21
      STOF(ISTOF + 22) = RT_22
      STOF(ISTOF + 23) = RT_23
      STOF(ISTOF + 24) = RT_24
      STOF(ISTOF + 25) = RT_25
      STOF(ISTOF + 26) = RT_26
      STOF(ISTOF + 27) = RT_27
      STOF(ISTOF + 28) = RT_28
      STOF(ISTOF + 29) = RT_29
      STOF(ISTOF + 30) = RT_30
      STOF(ISTOF + 31) = Eqctr
      STOF(ISTOF + 32) = RT_31
      STOF(ISTOF + 33) = RT_32
      STOF(ISTOF + 34) = g_boost
      STOF(ISTOF + 35) = RT_33
      STOF(ISTOF + 36) = RT_34
      STOF(ISTOF + 37) = RT_35
      STOF(ISTOF + 38) = RT_36
      STOF(ISTOF + 39) = RT_37
      STOF(ISTOF + 40) = RT_38
      STOF(ISTOF + 41) = RT_39
      STOF(ISTOF + 42) = RT_40
      STOF(ISTOF + 43) = RT_41
      STOF(ISTOF + 44) = RT_42
      STOF(ISTOF + 45) = RT_43
      STOF(ISTOF + 46) = RT_44
      STOF(ISTOF + 47) = RT_45
      STOF(ISTOF + 48) = M_boost
      STOI(ISTOI + 1) = g4
      STOF(ISTOF + 49) = g1
      STOF(ISTOF + 50) = g3
      STOF(ISTOF + 51) = g5
      STOI(ISTOI + 2) = g2
      STOI(ISTOI + 3) = g6
      STOF(ISTOF + 52) = Theta1
      STOF(ISTOF + 53) = f
      STOF(ISTOF + 54) = Va
      STOF(ISTOF + 55) = Vb
      STOF(ISTOF + 56) = Vc
      STOF(ISTOF + 57) = Vab
      STOF(ISTOF + 58) = Vbc
      STOF(ISTOF + 59) = Vca
      STOF(ISTOF + 60) = Ia
      STOF(ISTOF + 61) = Ib
      STOF(ISTOF + 62) = Ic
      STOF(ISTOF + 63) = Vtr
      STOF(ISTOF + 64) = Edctr
      STOF(ISTOF + 65) = Vq
      STOF(ISTOF + 66) = Vd
      STOF(ISTOF + 67) = Valpha
      STOF(ISTOF + 68) = Vbeta
      STOF(ISTOF + 69) = Ectr_alpha
      STOF(ISTOF + 70) = Ectr_beta
      STOF(ISTOF + 71) = Theta
      STOF(ISTOF + 72) = Iq
      STOF(ISTOF + 73) = Id
      STOF(ISTOF + 74) = Ibeta
      STOF(ISTOF + 75) = Ialpha
      STOF(ISTOF + 76) = Vdlimit
      STOF(ISTOF + 77) = Iqerf
      STOF(ISTOF + 78) = Vdcc
      STOF(ISTOF + 79) = Vdccn
      STOF(ISTOF + 80) = Iderf
      STOF(ISTOF + 81) = Van
      STOF(ISTOF + 82) = Vbn
      STOF(ISTOF + 83) = Vcn
      STOF(ISTOF + 84) = Pout
      STOF(ISTOF + 85) = Vbcn
      STOF(ISTOF + 86) = Vcan
      STOF(ISTOF + 87) = Vabn
      STOF(ISTOF + 88) = Ian
      STOF(ISTOF + 89) = Ibn
      STOF(ISTOF + 90) = Qout
      STOF(ISTOF + 91) = Icn
      STOF(ISTOF + 92) = scal
      STOF(ISTOF + 93) = Ectr_c
      STOF(ISTOF + 94) = Ectr_b
      STOF(ISTOF + 95) = Ectr_a
      STOF(ISTOF + 96) = Ectr_apu
      STOF(ISTOF + 97) = Ectr_bpu
      STOF(ISTOF + 98) = Ectr_cpu
      STOF(ISTOF + 99) = RT_46
      STOF(ISTOF + 100) = RT_47
      STOF(ISTOF + 101) = RT_48
      STOI(ISTOI + 4) = IT_1
      STOI(ISTOI + 5) = IT_2
      STOI(ISTOI + 6) = IT_3
      STOF(ISTOF + 102) = RT_49
      STOF(ISTOF + 103) = RT_50
      STOF(ISTOF + 104) = RT_51
      STOF(ISTOF + 105) = RT_52
      STOF(ISTOF + 106) = RT_53
      STOF(ISTOF + 107) = RT_54
      STOF(ISTOF + 108) = RT_55
      STOF(ISTOF + 109) = RT_56
      STOF(ISTOF + 110) = RT_57
      STOF(ISTOF + 111) = RT_58
      STOF(ISTOF + 112) = RT_59
      STOF(ISTOF + 113) = RT_60
      STOF(ISTOF + 114) = RT_61
      STOF(ISTOF + 115) = RT_62
      STOF(ISTOF + 116) = RT_63
      STOF(ISTOF + 117) = RT_64
      STOF(ISTOF + 118) = RT_65
      STOF(ISTOF + 119) = RT_66
      STOF(ISTOF + 120) = RT_67
      STOF(ISTOF + 121) = RT_68
      STOF(ISTOF + 122) = RT_69
      STOF(ISTOF + 123) = RT_70
      STOF(ISTOF + 124) = RT_71
      STOF(ISTOF + 125) = RT_72
      STOF(ISTOF + 126) = RT_73
      STOF(ISTOF + 127) = RT_74
      STOF(ISTOF + 128) = RT_75
      STOF(ISTOF + 129) = RT_76
      STOF(ISTOF + 130) = RT_77
      STOF(ISTOF + 131) = RT_78
      STOF(ISTOF + 132) = RT_79
      STOF(ISTOF + 133) = RT_80
      STOF(ISTOF + 134) = RT_81
      STOF(ISTOF + 135) = RT_82
      STOF(ISTOF + 136) = RT_83
      STOF(ISTOF + 137) = RT_84
      STOF(ISTOF + 138) = RT_85
      STOF(ISTOF + 139) = RT_86
      STOF(ISTOF + 140) = RT_87
      STOF(ISTOF + 141) = RT_88
      STOF(ISTOF + 142) = RT_89
      STOF(ISTOF + 143) = RT_90
      STOF(ISTOF + 144) = RT_91
      STOF(ISTOF + 145) = RT_92
      STOF(ISTOF + 146) = RT_93
      STOF(ISTOF + 147) = RT_94
      STOF(ISTOF + 148) = RT_95
      STOF(ISTOF + 149) = RT_96
      STOF(ISTOF + 150) = RT_97
      STOF(ISTOF + 151) = RT_98
      STOF(ISTOF + 152) = RT_99
      STOF(ISTOF + 153) = RT_100
      STOF(ISTOF + 154) = RT_101
      STOF(ISTOF + 155) = RT_102
      STOF(ISTOF + 156) = RT_103
      STOF(ISTOF + 157) = RT_104
      STOF(ISTOF + 158) = Vpv

!---------------------------------------
! Transfer to Exports
!---------------------------------------

!---------------------------------------
! Close Model Data read
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE DSOut()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'

!---------------------------------------
! Function/Subroutine Declarations
!---------------------------------------

      REAL    EMTDC_VVDC    ! 
      REAL    VBRANCH       ! Voltage across the branch

!---------------------------------------
! Variable Declarations
!---------------------------------------


! Electrical Node Indexes
      INTEGER NT_7, NT_9, NT_10, NT_14, NT_15
      INTEGER NT_16

! Control Signals
      REAL    RT_38, RT_39, RT_40, RT_41, RT_42
      REAL    RT_43, Va, Vb, Vc, Vab, Vbc, Vca
      REAL    Ia, Ib, Ic, Vdcc, Vdccn, Van, Vbn
      REAL    Vcn, Pout, Vbcn, Vcan, Vabn, Ian
      REAL    Ibn, Icn, RT_102, Vpv

! Internal Variables

! Indexing variables
      INTEGER ISTOL, ISTOI, ISTOF, IT_0           ! Storage Indexes
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr


!---------------------------------------
! Record local indexes
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage
      NTXFR = NTXFR + 1
      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)

! Record Offset and Increment Storage Counters
      IPGB      = NPGB
      NPGB      = NPGB + 32
      INODE     = NNODE + 2
      NNODE     = NNODE + 18

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO 100  IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
  100 CONTINUE

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 33

!---------------------------------------
! Transfers from storage arrays
!---------------------------------------

      RT_38    = STOF(ISTOF + 40)
      RT_39    = STOF(ISTOF + 41)
      RT_40    = STOF(ISTOF + 42)
      RT_41    = STOF(ISTOF + 43)
      RT_42    = STOF(ISTOF + 44)
      RT_43    = STOF(ISTOF + 45)
      Va       = STOF(ISTOF + 54)
      Vb       = STOF(ISTOF + 55)
      Vc       = STOF(ISTOF + 56)
      Vab      = STOF(ISTOF + 57)
      Vbc      = STOF(ISTOF + 58)
      Vca      = STOF(ISTOF + 59)
      Ia       = STOF(ISTOF + 60)
      Ib       = STOF(ISTOF + 61)
      Ic       = STOF(ISTOF + 62)
      Vdcc     = STOF(ISTOF + 78)
      Vdccn    = STOF(ISTOF + 79)
      Van      = STOF(ISTOF + 81)
      Vbn      = STOF(ISTOF + 82)
      Vcn      = STOF(ISTOF + 83)
      Pout     = STOF(ISTOF + 84)
      Vbcn     = STOF(ISTOF + 85)
      Vcan     = STOF(ISTOF + 86)
      Vabn     = STOF(ISTOF + 87)
      Ian      = STOF(ISTOF + 88)
      Ibn      = STOF(ISTOF + 89)
      Icn      = STOF(ISTOF + 91)
      RT_102   = STOF(ISTOF + 155)
      Vpv      = STOF(ISTOF + 158)

!---------------------------------------
! Electrical Node Lookup
!---------------------------------------

      NT_7  = NODE(INODE + 7)
      NT_9  = NODE(INODE + 9)
      NT_10 = NODE(INODE + 10)
      NT_14 = NODE(INODE + 14)
      NT_15 = NODE(INODE + 15)
      NT_16 = NODE(INODE + 16)

!---------------------------------------
! Read Model data (if any)
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Main.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF

!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 10:[voltmeter] Voltmeter (Line - Line) 'Vdcc'
      Vdcc = EMTDC_VVDC(SS(1), NT_10, NT_7)

! 20:[voltmeter] Voltmeter (Line - Line) 'Vpv'
      Vpv = EMTDC_VVDC(SS(1), NT_9, NT_7)

! 30:[ammeter] Current Meter 'Ia'
      Ia = ( CBR((IBRCH(1)+16), SS(1)))

! 40:[voltmeter] Voltmeter (Line - Line) 'Vab'
      Vab = EMTDC_VVDC(SS(1), NT_14, NT_15)

! 50:[ammeter] Current Meter 'Ib'
      Ib = ( CBR((IBRCH(1)+17), SS(1)))

! 60:[voltmeter] Voltmeter (Line - Line) 'Vbc'
      Vbc = EMTDC_VVDC(SS(1), NT_15, NT_16)

! 70:[voltmeter] Voltmeter (Line - Line) 'Vca'
      Vca = EMTDC_VVDC(SS(1), NT_16, NT_14)

! 80:[ammeter] Current Meter 'Ic'
      Ic = ( CBR((IBRCH(1)+18), SS(1)))

! 90:[voltmeter] Voltmeter (Line - Line) 'Vc'
      Vc = EMTDC_VVDC(SS(1), NT_16, 0)

! 100:[voltmeter] Voltmeter (Line - Line) 'Vb'
      Vb = EMTDC_VVDC(SS(1), NT_15, 0)

! 110:[voltmeter] Voltmeter (Line - Line) 'Va'
      Va = EMTDC_VVDC(SS(1), NT_14, 0)

! 120:[gain] Gain Block 
!  Gain
      Vabn = 1000.0 * Vab
!

! 130:[pgb] Output Channel 'Vabn'

      PGB(IPGB+1) = Vabn

! 150:[gain] Gain Block 
!  Gain
      Vbcn = 1000.0 * Vbc
!

! 160:[pgb] Output Channel 'Vbcn'

      PGB(IPGB+2) = Vbcn

! 170:[gain] Gain Block 
!  Gain
      Vcan = 1000.0 * Vca
!

! 180:[pgb] Output Channel 'Vcan'

      PGB(IPGB+3) = Vcan

! 210:[gain] Gain Block 
!  Gain
      Ian = 1000.0 * Ia
!

! 230:[pgb] Output Channel 'Ian'

      PGB(IPGB+4) = Ian

! 240:[gain] Gain Block 
!  Gain
      Ibn = 1000.0 * Ib
!

! 260:[pgb] Output Channel 'Ibn'

      PGB(IPGB+5) = Ibn

! 290:[gain] Gain Block 
!  Gain
      Icn = 1000.0 * Ic
!

! 310:[pgb] Output Channel 'Icn'

      PGB(IPGB+6) = Icn

! 420:[gain] Gain Block 
!  Gain
      Vdccn = 1000.0 * Vdcc
!

! 430:[pgb] Output Channel 'Vdcc'

      PGB(IPGB+8) = Vdccn

! 640:[mult] Multiplier 
!
      RT_41 = Ian * Vbcn
!

! 660:[mult] Multiplier 
!
      RT_42 = Ibn * Vcan
!

! 680:[mult] Multiplier 
!
      RT_43 = Icn * Vabn
!

! 770:[gain] Gain Block 
!  Gain
      Van = 1000.0 * Va
!

! 780:[gain] Gain Block 
!  Gain
      Vbn = 1000.0 * Vb
!

! 790:[gain] Gain Block 
!  Gain
      Vcn = 1000.0 * Vc
!

! 890:[mult] Multiplier 
!
      RT_38 = Ian * Van
!

! 910:[mult] Multiplier 
!
      RT_39 = Ibn * Vbn
!

! 920:[sumjct] Summing/Differencing Junctions 
      RT_102 = + RT_41 + RT_42 + RT_43
!

! 1680:[mult] Multiplier 
!
      RT_40 = Icn * Vcn
!

! 1700:[sumjct] Summing/Differencing Junctions 
      Pout = + RT_38 + RT_39 + RT_40
!

! 1850:[pgb] Output Channel 'Pout'

      PGB(IPGB+24) = Pout

! 1950:[pgb] Output Channel 'Vcn'

      PGB(IPGB+30) = Vcn

! 1980:[pgb] Output Channel 'Vbn'

      PGB(IPGB+31) = Vbn

! 2000:[pgb] Output Channel 'Van'

      PGB(IPGB+32) = Van

!---------------------------------------
! Feedbacks and transfers to storage
!---------------------------------------

      STOF(ISTOF + 40) = RT_38
      STOF(ISTOF + 41) = RT_39
      STOF(ISTOF + 42) = RT_40
      STOF(ISTOF + 43) = RT_41
      STOF(ISTOF + 44) = RT_42
      STOF(ISTOF + 45) = RT_43
      STOF(ISTOF + 54) = Va
      STOF(ISTOF + 55) = Vb
      STOF(ISTOF + 56) = Vc
      STOF(ISTOF + 57) = Vab
      STOF(ISTOF + 58) = Vbc
      STOF(ISTOF + 59) = Vca
      STOF(ISTOF + 60) = Ia
      STOF(ISTOF + 61) = Ib
      STOF(ISTOF + 62) = Ic
      STOF(ISTOF + 78) = Vdcc
      STOF(ISTOF + 79) = Vdccn
      STOF(ISTOF + 81) = Van
      STOF(ISTOF + 82) = Vbn
      STOF(ISTOF + 83) = Vcn
      STOF(ISTOF + 84) = Pout
      STOF(ISTOF + 85) = Vbcn
      STOF(ISTOF + 86) = Vcan
      STOF(ISTOF + 87) = Vabn
      STOF(ISTOF + 88) = Ian
      STOF(ISTOF + 89) = Ibn
      STOF(ISTOF + 91) = Icn
      STOF(ISTOF + 155) = RT_102
      STOF(ISTOF + 158) = Vpv

!---------------------------------------
! Close Model Data read
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

